Generate a unittest test script for the following Python function.
The script should fully test the function and be runnable directly.

### Output Formatting
1. Start with: import unittest
2. Include: from HumanEval_58_code import common
3. End with:
if __name__ == '__main__':
    unittest.main()

Function:
def common(l1: list, l2: list):
    """Return sorted unique common elements for two lists.
    >>> common([1, 4, 3, 34, 653, 2, 5], [5, 7, 1, 5, 9, 653, 121])
    [1, 5, 653]
    >>> common([5, 3, 2, 8], [3, 2])
    [2, 3]
    """
    ret = set()
    for e1 in l1:
        for e2 in l2:
            if e1 == e2:
                ret.add(e1)
    return sorted(list(ret))

 Here is a unittest test script for the provided function. I've added several test cases to cover various scenarios, including empty lists, duplicate elements, and non-matching lists.


import unittest
from HumanEval_58_code import common

class TestCommonFunction(unittest.TestCase):

    def test_common_empty_lists(self):
        self.assertListEqual(common([]), [])
        self.assertListEqual(common([1, 2, 3], []), [])

    def test_common_no_matches(self):
        self.assertListEqual(common([1, 2, 3], [4, 5, 6]), [])
        self.assertListEqual(common([1, 2, 3], [2, 4, 6]), [])

    def test_common_single_match(self):
        self.assertListEqual(common([1, 2, 3], [2, 4, 3]), [3])
        self.assertListEqual(common([1, 2, 3], [3, 2, 1]), [1, 2, 3])

    def test_common_multiple_matches(self):
        self.assertListEqual(common([1, 4, 3, 34, 653, 2, 5], [5, 7, 1, 5, 9, 653, 121]), [1, 5, 653])
        self.assertListEqual(common([5, 3, 2, 8], [3, 2]), [2, 3])

if __name__ == '__main__':
    unittest.main()


This script includes a TestCase class with several test methods, each testing a different scenario. The `assertListEqual` function is used to compare the expected output with the actual output generated by the function. The test script will run all the test methods when executed directly.