Generate a unittest test script for the following Python function.
The script should fully test the function and be runnable directly.

### Output Formatting
1. Start with: import unittest
2. Include: from HumanEval_106_code import f
3. End with:
if __name__ == '__main__':
    unittest.main()

Function:
def f(n):
    """ Implement the function f that takes n as a parameter,
    and returns a list of size n, such that the value of the element at index i is the factorial of i if i is even
    or the sum of numbers from 1 to i otherwise.
    i starts from 1.
    the factorial of i is the multiplication of the numbers from 1 to i (1 * 2 * ... * i).
    Example:
    f(5) == [1, 2, 6, 24, 15]
    """

    ret = []
    for i in range(1, n + 1):
        if i % 2 == 0:
            x = 1
            for j in range(1, i + 1):
                x *= j
            ret += [x]
        else:
            x = 0
            for j in range(1, i + 1):
                x += j
            ret += [x]
    return ret

 Here is a unittest test script for the provided function `f(n)`. The test script checks the function's behavior for various input values and verifies that the output matches the expected results.


import unittest
from HumanEval_106_code import f

class TestFunction(unittest.TestCase):

    def test_f_function(self):
        self.assertEqual(f(1), [1])
        self.assertEqual(f(2), [1, 1])
        self.assertEqual(f(3), [1, 2, 1])
        self.assertEqual(f(4), [1, 2, 6, 1])
        self.assertEqual(f(5), [1, 2, 6, 24, 15])
        self.assertEqual(f(6), [1, 2, 6, 24, 120, 72])
        self.assertEqual(f(7), [1, 2, 6, 24, 120, 5040, 40320])
        self.assertEqual(f(8), [1, 2, 6, 24, 120, 5040, 40320, 3628800])
        self.assertEqual(f(9), [1, 2, 6, 24, 120, 5040, 40320, 3628800, 36288000])

if __name__ == '__main__':
    unittest.main()


This test script includes a test case for the `f` function, which checks the function's behavior for various input values from 1 to 9. The test case uses the `assertEqual` method to compare the expected output with the actual output generated by the `f` function. If the output matches the expected result, the test passes; otherwise, it fails.